replicaCount: 1

image:
  repository: cr.msk.sbercloud.ru/aicloud-services/uikit2.0
  pullPolicy: Always
  tag: "a635f4bb"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  host: uikit.sbercloud.tech


