---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: uikit20
  name: uikit20
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: uikit20
  template:
    metadata:
      labels:
        app: uikit20
    spec:
      containers:
        - name: uikit20
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{.Values.image.pullPolicy }}
