apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2.devops.sbercloud.dev/oauth2/start?rd=$scheme://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth2.devops.sbercloud.dev/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
  name: uikit
spec:
  tls:
    - hosts:
        - uikit.devops.sbercloud.dev
      secretName: uikit-https-dev
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: uikit
              servicePort: 80
            path: /