---
apiVersion: v1
kind: Service
metadata:
  name: uikit20
  namespace: uikit20
  labels:
    app: uikit20
spec:
  selector:
    app: uikit20
  ports:
    - protocol: TCP
      targetPort: 80
      port: {{ .Values.service.port }}
  type: NodePort