---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: uikit20
  name: uikit20
  namespace: uikit20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uikit20
  template:
    metadata:
      labels:
        app: uikit20
    spec:
      containers:
        - name: uikit20
          image: __CI_CONTAINER_TAG__
          imagePullPolicy: "Always"
