---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uikit-product-old
  namespace: ui-uikit-product
  labels:
    app: uikit-product
    version: old
spec:
  replicas: 2
  selector:
    matchLabels:
      version: old
  template:
    metadata:
      labels:
        app: uikit-product
        version: old
      annotations:
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "64Mi"
    spec:
      containers:
      - name: uikit-product-old
        image: old
        env:
        - name: LOG_LEVEL
          value: 'infoGroups'
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "40m"
          requests:
            memory: "128Mi"
            cpu: "20m"
      imagePullSecrets:
      - name: docker-auth-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
